In [63]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, mean_squared_error
from math import sqrt
import numpy as np

#Import dataset

strikers_data= pd.read_csv('C:/Users/jesus/OneDrive/Documentos/STRIKERS_DATA_2.csv')  

# Split the data into features (X) and target variable (y)
X = strikers_data.drop(columns=['GOALS','Player_ID','SHIRT_N','Penalty','M_SEASON','ROUND_N'])
y = strikers_data['GOALS']

# Split the dataset into a training set and a testing set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Create a Linear Regression model
regr = LinearRegression()

# Fit the model to the training data
regr.fit(X_train, y_train)

# Make predictions on the test data
y_pred = regr.predict(X_test)

# Calculate the R-squared (R2) metric
r2 = r2_score(y_test, y_pred)

# Calculate Root Mean Squared Error (RMSE)
rmse = sqrt(mean_squared_error(y_test, y_pred))
#Root Mean Squared Error (RMSE) is a commonly used metric in regression problems to evaluate the performance of a predictive model.
#It measures the average magnitude of the residuals or prediction errors, providing valuable insights into the quality of the model's predictions.
print(f'R-squared (R2): {r2}')
print(f'Root Mean Squared Error (RMSE): {rmse}')

R-squared (R2): 0.17344959351198896
Root Mean Squared Error (RMSE): 0.7665424711014289

In [5]:
print(y_pred)

[ 9.60097741e-01  4.37047796e-01  2.51180701e-01  5.81094952e-01
  3.23384176e-01  6.92259608e-02  1.33184586e+00  1.04391450e+00
  3.77789251e-01  7.01728259e-01  4.27420493e-01  4.56320054e-01
  7.91003009e-01  4.31335821e-02  5.34794899e-01  1.07909418e+00
  3.91591469e-01  2.83237119e-01  4.24449150e-01  8.53213444e-01
  3.28364504e-01  3.09020860e-01  9.75036303e-01  5.78757426e-01
 -1.79595008e-01  9.70941375e-01  3.96054093e-01  4.09454731e-01
  7.26275424e-01  6.93853881e-02  8.89668157e-01  8.16812923e-01
  2.32639450e-01  4.14504262e-01  8.77826390e-01  1.40935995e+00
  1.41815808e+00  5.98578044e-01  5.50493874e-01  1.05255752e-01
  5.43917122e-01  2.05079497e-01  7.47516241e-01  7.85953218e-01
  9.70375425e-01  5.41808085e-01 -7.09209086e-02  1.48447628e-01
  9.01025131e-01  5.53450446e-01  6.94071527e-01  4.38344640e-01
 -7.77923701e-02  4.78225761e-01  5.66490885e-01  7.87063180e-01
  6.56013661e-02  2.70513263e-01  4.24824116e-01  8.89801343e-01
  5.18605548e-01  2.96368667e-01  3.06227073e-01  5.24281882e-01
  4.21079226e-01  3.05433240e-01  3.41029498e-01  1.21163106e-01
  2.15202878e-01  3.65609172e-01  4.36010293e-01  9.02684335e-01
 -6.73310803e-02 -2.25823351e-02  2.27743495e-01  5.26223842e-01
  6.64521273e-01  6.45309421e-01  1.04046875e+00  8.11504066e-01
  5.35424762e-01  5.71564277e-01  4.82861331e-01  8.04123721e-01
  5.49015644e-01  4.12275541e-01  8.21092447e-02 -1.62953924e-01
  3.44655470e-01  3.07885300e-01  4.96144836e-01  6.03714734e-01
  5.43469988e-01  5.91794658e-01  5.63572863e-01  8.01417167e-01
  7.67342207e-01  4.39124175e-01  2.97761558e-01 -6.98432315e-02
  1.34014285e+00  5.07333856e-01  8.28558388e-01  1.41254422e-01
  3.68439411e-01  1.92142582e-01  8.46007381e-01  6.08955361e-01
  2.60410948e-01  6.26856266e-01  4.36365545e-01  9.31690440e-01
  2.69200468e-01  6.90951146e-01  7.06175706e-01 -3.40689355e-01
  9.17519012e-01  4.51258799e-01  7.52328057e-01  2.76137392e-01
  3.05131169e-01  8.80469882e-01  4.90131669e-01  1.99166091e-01
  4.63443551e-01  4.84019875e-01  5.68816190e-01  8.40062443e-01
  1.29008303e+00  1.94109111e-01  8.39937995e-01  4.67491139e-01
  6.94452915e-01  2.49898379e-01 -9.02837748e-02  4.39082538e-01
  8.21493001e-01  5.63414359e-01  9.21364333e-01  3.12957206e-01
  2.18535506e-01  5.33919889e-01  5.07005455e-01  4.48224906e-01
  1.27693222e+00  4.98291013e-01  4.60948803e-01  3.06695319e-02
  9.71766985e-01  8.73363705e-01  4.42316725e-01  6.00597831e-01
  2.43992622e-01  3.57799555e-01  4.92672573e-01  6.49020247e-01
 -3.24782716e-01  1.53963552e-01  3.43516353e-02  6.03194396e-01
  7.95404013e-01  3.94843278e-01  1.46711689e-01  7.42104294e-01
  1.32388107e+00  7.71060694e-01  5.11524310e-01  4.78249282e-01
 -9.89367509e-02  9.71845288e-04  1.05621756e+00  3.51304166e-01
  4.31420492e-01  3.64647282e-01  4.82670578e-02  1.07776516e+00
  2.76934762e-01  1.37412350e+00  7.26138799e-01  5.85857695e-01
  3.91127901e-01  2.78548604e-01  2.97522299e-01  5.34864310e-01
  8.22806402e-01  8.05743603e-01  2.73147058e-02  8.06327112e-01
  4.14063913e-01  1.01830413e+00  5.03137746e-01  4.14376284e-01
  1.28939315e+00  5.67343993e-01  1.04529275e+00  6.43016938e-01
  6.61272291e-01  7.16723052e-01  4.55013658e-01]

In [64]:
# Create a DataFrame with 'predictions' and 'actual' columns
df = pd.DataFrame(data={'predictions': y_pred, 'actual': y_test})

# Print the DataFrame
pd.set_option('display.max_rows', None)
print(df)

     predictions  actual
213     1.004522       0
331     0.349943       0
501     0.321305       1
309     0.601865       2
88      0.393271       1
535     0.047820       0
280     1.378236       0
107     1.073611       3
59      0.400229       0
506     0.680838       1
359     0.296484       2
445     0.556820       0
70      0.826578       3
96      0.386191       0
858     0.313769       0
750     0.912703       1
864     0.184695       0
933     0.145497       1
76      0.423531       0
826     0.751883       1
198     0.273060       1
499     0.569610       1
710     1.058633       2
500     0.606328       0
536    -0.150485       0
790     0.895943       1
874     0.181359       0
518     0.628084       0
457     0.748963       3
945     0.166981       0
813     0.844202       3
728     0.869238       0
603     0.301507       0
597     0.331793       0
673     0.719640       0
689     1.270105       2
382     1.460438       2
939     0.435202       0
616     0.601150       0
655     0.085123       0
965     0.336134       0
23      0.415654       0
30      0.858246       1
730     0.905183       0
10      0.940687       1
174     0.420292       2
522    -0.055360       0
643     0.230412       0
721     0.999491       0
318     0.572964       2
139     0.678988       2
286     0.503965       0
926    -0.189670       0
485     0.541491       0
449     0.602020       0
832     0.674051       0
567     0.050541       0
362     0.163775       0
209     0.493135       0
591     0.804849       2
442     0.618873       1
265     0.194317       2
915     0.252791       0
281     0.569673       1
380     0.469243       0
39      0.467829       0
870     0.104635       0
857     0.109815       0
626     0.170442       0
66      0.422593       0
481     0.558652       0
67      0.958011       0
583    -0.094044       0
423    -0.031081       0
352     0.226346       1
261     0.399271       1
765     0.346332       1
780     0.565703       0
244     1.068731       0
811     0.714948       1
292     0.539577       0
424     0.559472       0
63      0.625554       0
817     0.706002       0
184     0.438585       2
596     0.307188       0
762    -0.050192       0
523    -0.172184       0
363     0.255231       1
538     0.255118       0
254     0.483395       0
806     0.624079       2
388     0.618391       0
684     0.544576       0
976     0.395018       1
545     0.751796       0
86      0.798273       0
644     0.455976       1
158     0.368000       0
548    -0.082229       0
830     1.282082       1
350     0.434695       0
697     0.910877       2
585     0.090596       0
756     0.140732       1
247     0.211847       0
940     0.729698       0
319     0.615490       1
433     0.362500       0
478     0.664208       0
618     0.508053       0
136     0.949259       1
931     0.273652       0
497     0.743480       0
986     0.512649       0
525    -0.245516       0
55      0.969916       0
863     0.280343       1
893     0.671690       1
439     0.359466       1
120     0.497153       3
25      0.989104       2
72      0.595921       1
850     0.003278       0
44      0.520694       0
672     0.371846       0
734     0.822063       1
621     0.905622       0
934     1.134383       1
929     0.039065       0
866     0.603043       0
260     0.351523       0
802     0.604114       0
221     0.371629       1
342    -0.130595       0
638     0.298572       1
299     0.872048       1
909     0.688555       0
898     0.834924       1
932     0.374367       0
266     0.187026       0
289     0.572134       1
60      0.537291       0
977     0.284726       0
432     1.385235       4
905     0.680486       1
666     0.396149       1
588     0.036835       0
168     0.976002       0
290     0.895262       0
884     0.369265       0
218     0.639840       0
210     0.341500       0
321     0.470321       0
199     0.368217       0
110     0.668141       0
916    -0.377645       0
521     0.149371       0
328    -0.013750       1
231     0.680059       0
796     0.706124       0
310     0.454296       0
861     0.013950       0
692     0.635130       0
788     1.226205       1
394     0.807514       2
451     0.605531       1
137     0.459131       0
344    -0.108468       0
420    -0.039542       1
715     1.139053       1
868     0.180928       0
759     0.213789       0
551     0.346944       0
544     0.069443       0
513     1.099169       2
853     0.043969       1
767     1.400812       2
803     0.633184       0
78      0.575016       1
29      0.494564       0
890     0.213966       0
899     0.264318       0
467     0.540502       0
731     0.979517       1
165     0.785906       2
557    -0.007839       0
482     0.860759       1
448     0.444837       0
65      1.062160       0
141     0.486496       2
630     0.392873       0
746     1.423735       4
450     0.600214       0
705     1.147365       0
305     0.673461       0
808     0.741770       0
237     0.743806       0
754     0.230185       0

In [65]:
df.sum()

predictions    102.408485
actual         107.000000
dtype: float64

In [66]:
y_pred_f = regr.predict(X)
strikers_data['goals_predicted']=y_pred_f
strikers_data.head(10)
player_pred = strikers_data.groupby(['Player_ID']).agg({'GOALS': 'sum', 'goals_predicted': 'sum'})
print(player_pred)

           GOALS  goals_predicted
Player_ID
BE-9          80        80.098423
CZ-10         17        17.902505
CZ-16          2         4.899060
DE-11         11         4.434648
DK-11          4         3.525348
DK-16         11        19.910808
ENG-9         62        59.112292
ES-19         34        39.558721
FR-10         46        42.675821
HR-7           2         8.310890
HU-20         12        13.230370
IT-19          4         2.224396
NL-10         44        40.300020
PL-9          69        63.420052
PT-7         116       112.620118
PT-9           8         5.361500
SC-9           5         4.901608
UA-9           8         7.921905

In [67]:
# Export to Excel
player_pred.to_excel('player_pred_r.xlsx', index=False)

In [59]:
#Import dataset

new_data= pd.read_csv('C:/Users/jesus/OneDrive/Documentos/prediction_temp.csv')  

# Split the data into features (X) and target variable (y)
X1 = new_data.drop(columns=['Player_ID','SHIRT_N','M_SEASON','ROUND_N'])
X1.head(10)

,AGE,HEIGHT,FOOT,SQUAD_RANKING,OPPONENT RANKING,M_WEEKDAY,M_MONTH,YEAR,COMPETITION_N,VENUE_N,STARTER,STRIKER,Penalty_shooter,MINUTES
0,39,187,1,6,36,2,6,2024,3,3,1,1,1,85
1,39,187,1,6,40,6,6,2024,3,3,1,1,1,85
2,39,187,1,6,75,3,6,2024,3,3,1,1,1,85
3,23,184,1,6,36,2,6,2024,3,3,0,1,0,25
4,23,184,1,6,40,6,6,2024,3,3,0,1,0,25
5,23,184,1,6,75,3,6,2024,3,3,0,1,0,25
6,31,192,2,3,48,1,6,2024,3,3,1,1,1,75
7,31,192,2,3,46,6,6,2024,3,3,1,1,1,75
8,31,192,2,3,22,3,6,2024,3,3,1,1,1,75
9,28,186,2,36,6,2,6,2024,3,3,1,1,1,75

In [60]:
y_new_pred = regr.predict(X1)
new_data['goals_predicted']=y_new_pred
new_data.head(10)

,Player_ID,SHIRT_N,AGE,HEIGHT,FOOT,SQUAD_RANKING,OPPONENT RANKING,M_WEEKDAY,M_MONTH,M_SEASON,YEAR,COMPETITION_N,ROUND_N,VENUE_N,STARTER,STRIKER,Penalty_shooter,MINUTES,goals_predicted
0,PT-7,7,39,187,1,6,36,2,6,2,2024,3,1,3,1,1,1,85,0.672659
1,PT-7,7,39,187,1,6,40,6,6,2,2024,3,1,3,1,1,1,85,0.664763
2,PT-7,7,39,187,1,6,75,3,6,2,2024,3,1,3,1,1,1,85,0.863904
3,PT-9,9,23,184,1,6,36,2,6,2,2024,3,1,3,0,1,0,25,0.332668
4,PT-9,9,23,184,1,6,40,6,6,2,2024,3,1,3,0,1,0,25,0.324772
5,PT-9,9,23,184,1,6,75,3,6,2,2024,3,1,3,0,1,0,25,0.523913
6,BE-9,9,31,192,2,3,48,1,6,2,2024,3,1,3,1,1,1,75,0.957233
7,BE-9,9,31,192,2,3,46,6,6,2,2024,3,1,3,1,1,1,75,0.911770
8,BE-9,9,31,192,2,3,22,3,6,2,2024,3,1,3,1,1,1,75,0.810914
9,CZ-10,10,28,186,2,36,6,2,6,2,2024,3,1,3,1,1,1,75,0.416472

In [62]:
player_pred_euro24_R = new_data.groupby(['Player_ID']).agg({'goals_predicted': 'sum'})
print(player_pred_euro24_R)
# Export to Excel
player_pred_euro24_R.to_excel('multi_reg.xlsx', index=False)

           goals_predicted
Player_ID
BE-9              2.679917
CZ-10             1.737845
CZ-16             0.212392
DE-11             0.613779
DK-11             1.810018
DK-16             0.547356
ENG-9             2.091574
ES-19             1.771069
FR-10             1.743917
HR-7              1.289309
HU-20             0.440677
IT-19             0.671570
NL-10             1.429648
PL-9              1.011175
PT-7              2.201326
PT-9              1.181353
SC-9              0.447071
UA-9              1.658674