In [46]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.model_selection import train_test_split
from sklearn.linear_model import PoissonRegressor

#Import dataset

strikers_data= pd.read_csv('C:/Users/jesus/OneDrive/Documentos/STRIKERS_DATA_2.csv')  

# Split the data into features (X) and target variable (y)
X = strikers_data.drop(columns=['GOALS','Player_ID','SHIRT_N','Penalty','M_SEASON','ROUND_N'])
y = strikers_data['GOALS']

# Split the dataset into a training set and a testing set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialize the Random Forest regressor
clf = PoissonRegressor()

# Fit the model to the training data
clf.fit(X_train, y_train)


# Predict on the test set
y_pred = clf.predict(X_test)

# Evaluate the model
r_squared = clf.score(X, y)
print(f"R-squared: {r_squared:.3f}")

R-squared: 0.180

C:\Users\jesus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\sklearn\linear_model\_glm\glm.py:285: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res)

In [47]:
# Create a DataFrame with 'predictions' and 'actual' columns
df = pd.DataFrame(data={'predictions': y_pred, 'actual': y_test})

# Print the DataFrame
pd.set_option('display.max_rows', None)
print(df)

     predictions  actual
213     0.996218       0
331     0.424783       0
501     0.311610       1
309     0.519703       2
88      0.363791       1
535     0.170375       0
280     1.532661       0
107     1.222542       3
59      0.467072       0
506     0.567369       1
359     0.385458       2
445     0.348619       0
70      0.994204       3
96      0.254307       0
858     0.474213       0
750     1.012907       1
864     0.468023       0
933     0.226703       1
76      0.512664       0
826     0.692063       1
198     0.333684       1
499     0.480744       1
710     0.903456       2
500     0.503829       0
536     0.107157       0
790     0.941021       1
874     0.378521       0
518     0.669930       0
457     0.641924       3
945     0.199740       0
813     0.662276       3
728     0.672074       0
603     0.258296       0
597     0.353628       0
673     0.691481       0
689     1.593789       2
382     1.693137       2
939     0.413654       0
616     0.351577       0
655     0.183583       0
965     0.352942       0
23      0.427305       0
30      0.917900       1
730     0.714288       0
10      1.366743       1
174     0.567407       2
522     0.119134       0
643     0.217671       0
721     0.751413       0
318     0.445911       2
139     0.750842       2
286     0.389691       0
926     0.164725       0
485     0.486188       0
449     0.520082       0
832     0.652643       0
567     0.171683       0
362     0.342274       0
209     0.412462       0
591     0.749147       2
442     0.404759       1
265     0.370198       2
915     0.205928       0
281     0.385432       1
380     0.464465       0
39      0.429988       0
870     0.446726       0
857     0.414931       0
626     0.167855       0
66      0.527122       0
481     0.355764       0
67      1.090040       0
583     0.160265       0
423     0.220056       0
352     0.232051       1
261     0.420634       1
765     0.542405       1
780     0.571153       0
244     1.056990       0
811     0.704257       1
292     0.496954       0
424     0.497048       0
63      0.729040       0
817     0.683085       0
184     0.583208       2
596     0.353017       0
762     0.213808       0
523     0.104906       0
363     0.337376       1
538     0.240028       0
254     0.321038       0
806     0.515737       2
388     0.486747       0
684     0.561984       0
976     0.368452       1
545     0.611096       0
86      0.751405       0
644     0.422988       1
158     0.260472       0
548     0.131847       0
830     1.350840       1
350     0.402205       0
697     0.679489       2
585     0.154575       0
756     0.440372       1
247     0.204422       0
940     0.458360       0
319     0.555515       1
433     0.252369       0
478     0.531405       0
618     0.223225       0
136     1.117344       1
931     0.395453       0
497     0.624000       0
986     0.451610       0
525     0.083094       0
55      1.082919       0
863     0.541449       1
893     0.392849       1
439     0.294932       1
120     0.592884       3
25      0.900325       2
72      0.653609       1
850     0.383405       0
44      0.586784       0
672     0.384018       0
734     0.663700       1
621     0.692178       0
934     1.209491       1
929     0.262905       0
866     0.761272       0
260     0.380766       0
802     0.578595       0
221     0.368664       1
342     0.146613       0
638     0.292558       1
299     0.667391       1
909     0.295346       0
898     0.564542       1
932     0.352181       0
266     0.363924       0
289     0.370951       1
60      0.576155       0
977     0.323172       0
432     1.269789       4
905     0.342713       1
666     0.339968       1
588     0.184205       0
168     1.144727       0
290     0.643056       0
884     0.265672       0
218     0.511393       0
210     0.281456       0
321     0.280436       0
199     0.544567       0
110     0.667548       0
916     0.080601       0
521     0.165484       0
328     0.162463       1
231     0.475459       0
796     0.647838       0
310     0.412490       0
861     0.323885       0
692     0.502746       0
788     1.425446       1
394     0.642352       2
451     0.624368       1
137     0.567982       0
344     0.201370       0
420     0.190570       1
715     1.011175       1
868     0.388762       0
759     0.419152       0
551     0.305811       0
544     0.143590       0
513     0.983127       2
853     0.343802       1
767     1.841192       2
803     0.570497       0
78      0.639099       1
29      0.524164       0
890     0.206588       0
899     0.201478       0
467     0.443476       0
731     0.675929       1
165     0.856017       2
557     0.172802       0
482     0.708257       1
448     0.409899       0
65      1.275772       0
141     0.562443       2
630     0.340505       0
746     0.906311       4
450     0.617176       0
705     0.982540       0
305     0.509643       0
808     0.897324       0
237     0.599067       0
754     0.518183       0

In [48]:
df.sum()

predictions    105.900717
actual         107.000000
dtype: float64

In [49]:
y_pred_f = clf.predict(X)

In [50]:
strikers_data['goals_predicted']=y_pred_f
strikers_data.head(10)

,Player_ID,SHIRT_N,AGE,HEIGHT,FOOT,SQUAD_RANKING,OPPONENT RANKING,M_WEEKDAY,M_MONTH,M_SEASON,...,COMPETITION_N,ROUND_N,VENUE_N,STARTER,STRIKER,Penalty,Penalty_shooter,MINUTES,GOALS,goals_predicted
0,PT-7,7,19,187,1,9,18,7,6,2,...,3,1,1,0,0,0,0,45,1,0.247812
1,PT-7,7,19,187,1,9,32,4,6,2,...,3,1,2,0,0,0,0,13,0,0.189186
2,PT-7,7,19,187,1,9,5,1,6,2,...,3,1,2,1,0,0,0,84,0,0.404530
3,PT-7,7,19,187,1,9,8,5,6,2,...,3,3,1,1,0,0,0,120,0,0.623264
4,PT-7,7,19,187,1,9,6,4,6,2,...,3,4,1,1,0,0,0,66,1,0.313388
5,PT-7,7,19,187,1,9,18,1,7,2,...,3,5,1,1,0,0,0,90,0,0.495026
6,PT-7,7,20,187,1,9,65,7,9,3,...,2,1,2,1,0,0,0,81,1,0.576472
7,PT-7,7,20,187,1,9,81,4,9,3,...,2,1,1,1,0,0,0,90,1,0.782396
8,PT-7,7,20,187,1,9,142,7,10,3,...,2,1,2,1,0,0,0,61,0,0.805628
9,PT-7,7,20,187,1,9,32,4,10,3,...,2,1,1,1,0,0,0,84,2,0.505004

In [51]:
player_pred = strikers_data.groupby(['Player_ID']).agg({'GOALS': 'sum', 'goals_predicted': 'sum'})

print(player_pred)

           GOALS  goals_predicted
Player_ID
BE-9          80        69.418777
CZ-10         17        10.523751
CZ-16          2         7.125306
DE-11         11         4.697345
DK-11          4         4.007452
DK-16         11        16.984764
ENG-9         62        62.653984
ES-19         34        39.623018
FR-10         46        38.897016
HR-7           2        18.481120
HU-20         12        15.327477
IT-19          4         2.945074
NL-10         44        38.843395
PL-9          69        56.722417
PT-7         116       126.318478
PT-9           8         5.680594
SC-9           5         7.200116
UA-9           8         8.379084

In [21]:
pip install openpyxl

Defaulting to user installation because normal site-packages is not writeableNote: you may need to restart the kernel to use updated packages.

Collecting openpyxl
  Downloading openpyxl-3.1.3-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-1.1.0-py3-none-any.whl.metadata (1.8 kB)
Downloading openpyxl-3.1.3-py2.py3-none-any.whl (251 kB)
   ---------------------------------------- 0.0/251.3 kB ? eta -:--:--
   - -------------------------------------- 10.2/251.3 kB ? eta -:--:--
   - -------------------------------------- 10.2/251.3 kB ? eta -:--:--
   ---- ---------------------------------- 30.7/251.3 kB 330.3 kB/s eta 0:00:01
   --------- ----------------------------- 61.4/251.3 kB 409.6 kB/s eta 0:00:01
   ----------------- -------------------- 112.6/251.3 kB 595.3 kB/s eta 0:00:01
   ---------------------------------------  245.8/251.3 kB 1.1 MB/s eta 0:00:01
   ---------------------------------------  245.8/251.3 kB 1.1 MB/s eta 0:00:01
   -------------------------------------- 251.3/251.3 kB 858.0 kB/s eta 0:00:00
Downloading et_xmlfile-1.1.0-py3-none-any.whl (4.7 kB)
Installing collected packages: et-xmlfile, openpyxl
Successfully installed et-xmlfile-1.1.0 openpyxl-3.1.3

In [53]:
# Export to Excel
player_pred.to_excel('player_pred.xlsx', index=False)

In [38]:
#Import dataset

new_data= pd.read_csv('C:/Users/jesus/OneDrive/Documentos/prediction_temp.csv')  

# Split the data into features (X) and target variable (y)
X1 = new_data.drop(columns=['Player_ID','SHIRT_N','M_SEASON','ROUND_N'])

In [39]:
X1.head(10)

,AGE,HEIGHT,FOOT,SQUAD_RANKING,OPPONENT RANKING,M_WEEKDAY,M_MONTH,YEAR,COMPETITION_N,VENUE_N,STARTER,STRIKER,Penalty_shooter,MINUTES
0,39,187,1,6,36,2,6,2024,3,3,1,1,1,85
1,39,187,1,6,40,6,6,2024,3,3,1,1,1,85
2,39,187,1,6,75,3,6,2024,3,3,1,1,1,85
3,23,184,1,6,36,2,6,2024,3,3,0,1,0,25
4,23,184,1,6,40,6,6,2024,3,3,0,1,0,25
5,23,184,1,6,75,3,6,2024,3,3,0,1,0,25
6,31,192,2,3,48,1,6,2024,3,3,1,1,1,75
7,31,192,2,3,46,6,6,2024,3,3,1,1,1,75
8,31,192,2,3,22,3,6,2024,3,3,1,1,1,75
9,28,186,2,36,6,2,6,2024,3,3,1,1,1,75

In [40]:
y_new_pred = clf.predict(X1)

In [41]:
new_data['goals_predicted']=y_new_pred
new_data.head(10)

,Player_ID,SHIRT_N,AGE,HEIGHT,FOOT,SQUAD_RANKING,OPPONENT RANKING,M_WEEKDAY,M_MONTH,M_SEASON,YEAR,COMPETITION_N,ROUND_N,VENUE_N,STARTER,STRIKER,Penalty_shooter,MINUTES,goals_predicted
0,PT-7,7,39,187,1,6,36,2,6,2,2024,3,1,3,1,1,1,85,0.767572
1,PT-7,7,39,187,1,6,40,6,6,2,2024,3,1,3,1,1,1,85,0.736303
2,PT-7,7,39,187,1,6,75,3,6,2,2024,3,1,3,1,1,1,85,1.012268
3,PT-9,9,23,184,1,6,36,2,6,2,2024,3,1,3,0,1,0,25,0.239790
4,PT-9,9,23,184,1,6,40,6,6,2,2024,3,1,3,0,1,0,25,0.230022
5,PT-9,9,23,184,1,6,75,3,6,2,2024,3,1,3,0,1,0,25,0.316233
6,BE-9,9,31,192,2,3,48,1,6,2,2024,3,1,3,1,1,1,75,0.754344
7,BE-9,9,31,192,2,3,46,6,6,2,2024,3,1,3,1,1,1,75,0.679238
8,BE-9,9,31,192,2,3,22,3,6,2,2024,3,1,3,1,1,1,75,0.597943
9,CZ-10,10,28,186,2,36,6,2,6,2,2024,3,1,3,1,1,1,75,0.245532

In [44]:
player_pred_euro24_P = new_data.groupby(['Player_ID']).agg({'goals_predicted': 'sum'})

print(player_pred_euro24_P)

           goals_predicted
Player_ID
BE-9              2.031526
CZ-10             0.942221
CZ-16             0.391201
DE-11             0.682036
DK-11             1.217785
DK-16             0.567009
ENG-9             1.950634
ES-19             1.606506
FR-10             1.401849
HR-7              1.398387
HU-20             0.902667
IT-19             0.614476
NL-10             1.277120
PL-9              1.099440
PT-7              2.516143
PT-9              0.786044
SC-9              0.712293
UA-9              1.314204

In [45]:
# Export to Excel
player_pred_euro24_P.to_excel('poisson_reg.xlsx', index=False)